<a href="https://colab.research.google.com/github/javendaXgh/ucveconomiaestadistica1/blob/main/notebooks/Clase_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Estadística I, Clase 7
## Tablas de Frecuencias Acumuladas

### Instalar paquetes requeridos

In [1]:
install.packages("openintro")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘airports’, ‘cherryblossom’, ‘usdata’

### Cargar librerías

In [2]:
library(openintro)
library(dplyr)

Loading required package: airports

Loading required package: cherryblossom

Loading required package: usdata


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

### Crear muestra pseudo aleatoria
Vamos a generar una muestra simulando un grupo de 9 estudiantes que tienen edades entre 20 y 25 años

In [3]:
set.seed(1234)
# x= población de la cuál se obtendrá la muestra
# size= cantidad de elementos que tendrá la muestra
# replace= establece sin en la muestra se pueden repetir elementos contenidos en x

muestra = sample(x=20:25,size = 9, replace= TRUE)

muestra

[1] 23 21 25 24 23 20 24 25 23

### Crear tabla de frecuencia para 3 intervalos

1) las clases <br>
2) punto medio (Xi)<br>
3) frecuencia absoluta (fi)<br>
4) frecuencia relativa (hi)<br>
5) frecuencia absoluta acumulada (Fi)<br>
6) frecuencia acumulada relativa (Hi)

### Ejercicio Nacimientos Babies

In [4]:
head(babies)

  case bwt gestation parity age height weight smoke
1 1    120 284       0      27  62     100    0
2 2    113 282       0      33  64     135    0
3 3    128 279       0      28  64     115    1
4 4    123  NA       0      36  69     190    0
5 5    108 282       0      23  67     125    1
6 6    136 286       0      25  62      93    0

In [5]:
edad_madres= babies$age[!is.na(babies$age)]
edad_madres

   [1] 27 33 28 36 23 25 33 23 25 30 27 32 23 36 30 38 25 33 33 43 22 27 25 30
  [25] 23 27 26 20 32 28 26 34 30 23 24 22 24 23 27 31 30 23 26 27 37 27 32 25
  [49] 26 26 26 31 28 31 30 22 26 33 28 33 24 22 23 23 28 36 37 26 31 38 27 26
  [73] 25 24 24 21 26 39 27 27 35 23 25 33 30 29 32 37 22 24 33 28 27 31 23 22
  [97] 28 37 35 29 27 33 24 36 24 37 33 22 27 29 26 28 19 21 22 29 33 25 32 39
 [121] 24 26 35 34 31 25 23 30 35 28 25 20 25 24 25 31 24 28 21 27 39 32 25 30
 [145] 32 23 24 29 24 38 29 29 29 20 23 21 22 24 39 22 21 43 36 30 22 22 29 26
 [169] 23 29 22 25 24 23 30 31 30 25 32 25 23 23 23 29 21 34 25 24 20 28 35 22
 [193] 26 32 26 30 22 22 22 34 19 25 20 23 21 23 22 26 38 29 19 25 23 28 21 33
 [217] 27 34 26 22 28 24 20 20 26 35 28 23 21 23 22 33 42 19 31 33 22 23 24 30
 [241] 22 25 27 27 25 21 32 28 24 24 38 23 21 29 26 31 22 21 30 23 28 30 27 22
 [265] 25 23 40 39 23 38 25 22 35 20 42 29 20 19 40 20 30 36 33 23 27 21 28 27
 [289] 20 27 22 35 20 23 25 36 34 26 26 29 25 24 27 21 26 19 29 24 18 32 29 34
 [313] 30 25 31 35 24 29 25 25 21 31 24 33 34 21 39 25 28 29 29 23 22 23 32 26
 [337] 23 31 22 32 30 27 30 25 22 37 42 23 22 24 31 33 27 18 19 22 40 24 22 24
 [361] 27 32 30 19 23 19 30 26 32 39 26 26 23 39 27 30 22 28 24 20 26 18 24 40
 [385] 31 31 23 26 25 21 22 22 19 27 34 30 24 23 29 22 25 26 26 24 22 39 25 22
 [409] 35 32 33 19 20 23 27 30 26 28 18 27 20 19 33 26 23 28 17 31 23 21 30 20
 [433] 39 30 32 24 27 26 24 28 27 27 38 22 21 24 24 21 40 20 29 32 33 27 32 25
 [457] 41 28 17 23 32 19 37 25 23 29 19 25 23 27 25 41 21 21 35 25 28 24 20 26
 [481] 37 27 23 24 33 25 24 21 21 22 19 19 26 31 21 31 26 37 31 26 29 20 15 31
 [505] 35 27 20 28 25 21 29 28 22 29 31 20 25 24 23 34 28 26 28 32 21 26 20 40
 [529] 19 19 25 37 24 30 20 30 20 19 25 27 30 33 23 23 21 20 24 25 28 26 26 20
 [553] 22 29 37 30 26 27 43 36 22 23 41 27 25 41 27 41 40 23 22 17 26 29 24 32
 [577] 36 25 24 22 31 28 21 22 26 19 22 30 29 31 36 35 21 25 20 17 26 25 37 19
 [601] 24 22 24 24 23 27 23 23 26 36 25 26 28 25 23 24 20 18 27 26 33 32 22 36
 [625] 23 27 34 24 26 21 19 44 21 28 31 21 24 29 35 37 35 18 37 40 34 25 27 20
 [649] 31 26 26 29 38 19 27 21 27 33 30 28 26 31 20 29 23 31 33 20 26 28 28 27
 [673] 24 37 26 28 27 29 28 25 28 19 39 29 38 34 29 22 27 25 20 35 29 38 39 26
 [697] 28 23 21 25 26 34 38 23 23 34 28 26 27 23 26 28 32 30 22 33 24 20 27 22
 [721] 23 34 33 39 20 20 23 33 20 29 27 34 30 34 28 33 19 19 22 27 19 21 21 22
 [745] 22 25 35 24 22 35 26 26 26 30 22 33 31 21 31 34 32 24 20 27 30 20 30 19
 [769] 24 32 23 26 27 35 24 29 27 25 29 20 38 34 25 38 23 30 27 29 25 22 21 30
 [793] 26 29 19 28 21 29 29 31 34 29 30 38 20 28 37 26 24 23 30 28 29 38 30 29
 [817] 28 28 20 39 41 38 19 20 32 26 23 24 33 37 27 19 26 39 36 28 27 25 22 32
 [841] 27 20 23 18 34 28 29 32 22 27 35 32 26 29 33 39 41 22 21 17 31 21 26 26
 [865] 27 41 21 27 30 29 32 36 25 19 22 34 30 19 26 18 22 23 30 28 27 28 35 27
 [889] 24 22 22 20 30 23 18 31 26 24 27 28 28 28 39 24 26 20 23 27 26 30 34 24
 [913] 19 27 40 27 31 31 28 35 27 25 23 25 26 38 33 26 24 30 37 21 26 29 21 23
 [937] 37 27 22 22 34 43 20 35 28 34 24 22 26 26 22 33 36 20 41 22 21 19 23 23
 [961] 43 19 32 30 28 35 19 23 21 36 21 22 33 31 26 43 35 19 21 27 33 28 30 27
 [985] 27 29 25 20 25 24 23 19 37 37 39 25 27 21 29 37 22 37 23 36 23 32 27 29
[1009] 19 36 20 30 23 24 36 29 40 26 36 33 36 36 30 28 20 25 34 31 25 21 24 30
[1033] 28 31 28 23 21 27 23 34 24 34 26 19 23 36 24 32 20 29 18 22 30 23 31 26
[1057] 33 31 30 24 27 29 19 24 21 39 24 21 45 32 41 25 22 34 26 30 21 33 19 23
[1081] 36 22 41 29 28 26 20 26 27 31 33 26 31 25 24 24 23 39 26 27 35 37 19 18
[1105] 37 20 35 28 24 23 31 21 24 20 30 29 30 23 35 39 30 22 37 19 21 42 40 41
[1129] 29 24 29 18 19 41 31 25 20 24 23 32 26 22 29 29 35 27 25 37 35 41 18 28
[1153] 25 23 29 28 19 19 26 23 34 24 20 25 37 30 32 19 21 21 26 27 21 25 25 23
[1177] 17 31 24 32 20 24 20 39 21 36 37 18 24 24 39 24 36 24 33 19 34 19 22 22
[1201] 32 25 31 29 17 18 29 25 33 21 28 39 21 28 24 28 19 28 19 21 21 23 28 29
[1225] 21 30 34 27 27 27 24 30 21 38

In [6]:
resultado <- hist(edad_madres, breaks = 5, plot=F)

In [7]:
resultado

$breaks
[1] 15 20 25 30 35 40 45

$counts
[1] 134 402 374 190 108  26

$density
[1] 0.021717990 0.065153971 0.060615883 0.030794165 0.017504052 0.004213938

$mids
[1] 17.5 22.5 27.5 32.5 37.5 42.5

$xname
[1] "edad_madres"

$equidist
[1] TRUE

attr(,"class")
[1] "histogram"

In [10]:
data.frame(Xi=resultado$mids,
           fi=resultado$counts,
           densidad= resultado$density)%>%
  mutate(hi= (fi/sum(resultado$counts)*100))%>%
  mutate(Fi= cumsum(fi))%>%
  mutate(HI= cumsum(fi/sum(resultado$counts)*100))

  Xi   fi  densidad    hi        Fi   HI
1 17.5 134 0.021717990 10.858995  134  10.85900
2 22.5 402 0.065153971 32.576985  536  43.43598
3 27.5 374 0.060615883 30.307942  910  73.74392
4 32.5 190 0.030794165 15.397083 1100  89.14100
5 37.5 108 0.017504052  8.752026 1208  97.89303
6 42.5  26 0.004213938  2.106969 1234 100.00000

### Visualización Histogramas Conjuntos de Datos

In [ ]:
hist(classdata$m1)

In [ ]:
hist(babies$age)

In [ ]:
hist(babies$height)

In [ ]:
hist(babies$weight)

In [ ]:
hist(babies$gestation,breaks =20)

In [ ]:
hist(age_at_mar$age)

In [ ]:
hist(arbuthnot$year, breaks = 50)

In [ ]:
# frecuencia relativa
hist(gpa_iq$gpa, freq=FALSE)

In [ ]:
hist(gpa_iq$gpa)

In [11]:
resultado2 <- hist(gpa_iq$gpa, breaks = 5, plot=F)

In [12]:
data.frame(Xi=resultado2$mids,
           fi=resultado2$counts,
           densidad= resultado2$density
           )%>%
  mutate(hi= (fi/sum(resultado2$counts)*100))%>%
  mutate(Fi= cumsum(fi))%>%
  mutate(HI= cumsum(fi/sum(resultado2$counts)*100))

  Xi fi densidad   hi        Fi HI
1  1  2 0.01282051  2.564103  2   2.564103
2  3  6 0.03846154  7.692308  8  10.256410
3  5  8 0.05128205 10.256410 16  20.512821
4  7 30 0.19230769 38.461538 46  58.974359
5  9 28 0.17948718 35.897436 74  94.871795
6 11  4 0.02564103  5.128205 78 100.000000

### Enlace Aplicación Pib PerCápita Países 2007
[aplicación gapminder](https://javenda.shinyapps.io/gapminder2007/)

### Enlace códigos aplicaciones
[código app gapminder](https://github.com/javendaXgh/ucveconomiaestadistica1/blob/main/apps/app_gapminder.R)

[código app edades madres](https://github.com/javendaXgh/ucveconomiaestadistica1/blob/main/apps/app_edadmadres.R)